import java.sql.Connection;
       import java.sql.Statement;
       import java.sql.ResultSet;
       import java.sql.DriverManager;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * adharcardlist.java
 *
 * Created on Aug 6, 2014, 12:19:57 AM
 */

/**
 *
 * @author 1
 */
public class adharcardlist extends javax.swing.JFrame {

    /** Creates new form adharcardlist */
    public adharcardlist() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        se = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        d1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(0);
        setTitle("ADHAAR CARD LIST ");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setText("BACK");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 112, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Delete Adharcard");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, -1, -1));

        jLabel1.setText("Enter Adharcard No.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, 25));

        se.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seActionPerformed(evt);
            }
        });
        getContentPane().add(se, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 176, 25));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 240, -1, -1));

        d1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ADHAR NO.", "NAME", "F.NAME", "D.O.B", "QUALIFICATION", "OCCUPATION", "ADDRESS", "CITY", "CONTACT.NO", "GENDER", "MARITAL STATUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        d1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(d1);
        if (d1.getColumnModel().getColumnCount() > 0) {
            d1.getColumnModel().getColumn(0).setPreferredWidth(10);
            d1.getColumnModel().getColumn(1).setPreferredWidth(120);
            d1.getColumnModel().getColumn(2).setPreferredWidth(130);
            d1.getColumnModel().getColumn(3).setPreferredWidth(5);
            d1.getColumnModel().getColumn(4).setPreferredWidth(30);
            d1.getColumnModel().getColumn(5).setPreferredWidth(30);
            d1.getColumnModel().getColumn(6).setPreferredWidth(100);
            d1.getColumnModel().getColumn(7).setPreferredWidth(20);
            d1.getColumnModel().getColumn(8).setPreferredWidth(15);
            d1.getColumnModel().getColumn(9).setPreferredWidth(1);
            d1.getColumnModel().getColumn(10).setPreferredWidth(40);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 120));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Show all");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 130, -1, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("Reset");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a2.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-220, 100, 1500, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
DefaultTableModel model=(DefaultTableModel)d1.getModel();
try
{
    Class.forName("java.sql.DriverManager");
    Connection c=(Connection)DriverManager.getConnection
            ("jdbc:mysql://localhost:3306/ovs","root","RRMPS");
    Statement S=(Statement)c.createStatement();
        String query="select * from ADHARCARD;";
        ResultSet rs=S.executeQuery(query);
        while(rs.next())
        {


        String sn=rs.getString("ADH");
        String un=rs.getString("NAME");
        String cn=rs.getString("FNAME");
        String pass=rs.getString("DOB");
        String pn=rs.getString("QU");
        String jn=rs.getString("O");
        String cs=rs.getString("A");
        String rn=rs.getString("C");
        String cno=rs.getString("CNO");
        String ge=rs.getString("G");
        String ms=rs.getString("S");
      
        model.addRow(new Object[]
        {sn,un,cn,pass,pn,jn,cs,rn,cno,ge,ms});

        }
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(null,e.getMessage());
}        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
int i=JOptionPane.showConfirmDialog(this,"Do you Want To Exit");
if(i==0)
{this.dispose();}        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
this.dispose();       // TODO add your handling code here:
}//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed


        int mid=d1.getSelectedRow();
        String k=(""+d1.getValueAt(mid,0));

int a[]=d1.getSelectedRows();
        
        DefaultTableModel dm=(DefaultTableModel)d1.getModel();
int n=JOptionPane.showConfirmDialog(this,"Are you sure to delete this ADHARCARD permanently");
if(n==0)
{
        try{
            Class.forName("java.sql.DriverManager");
            Connection c=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/ovs","root","RRMPS");
            Statement s=(Statement)c.createStatement();
            Statement S1=(Statement)c.createStatement();
            String q="delete from ADHARCARD where ADH =" + k +" ;";

       String query2="delete from REGISTRATION where ADHARCARDNO =" + k +" ;";
            s.executeUpdate(q);
             S1.executeUpdate(query2);
            
            JOptionPane.showMessageDialog(this,"ADHARCARD Deleted!!!","Delete",1);
            dm.removeRow(a[0]);
             } catch(Exception e) {
            JOptionPane.showMessageDialog(this,"ADHARCARD Not Selected","Error",0);
        }}
       
        // TODO add your handling code here:
        


}//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
int b=Integer.parseInt(se.getText());
DefaultTableModel model=(DefaultTableModel)d1.getModel();
{ {

}

    try
{
    Class.forName("java.sql.DriverManager");
    Connection c=(Connection)DriverManager.getConnection
            ("jdbc:mysql://localhost:3306/ovs","root","RRMPS");
    Statement S=(Statement)c.createStatement();
        String query="select * from ADHARCARD where  ADH='"+b+"';";
        ResultSet rs=S.executeQuery(query);
        
{
       int i=model.getRowCount();
while (i>0)
{
model.removeRow(0);
i--;
while(rs.next())
        {
            


        String sn=rs.getString("ADH");
        String un=rs.getString("NAME");
        String cn=rs.getString("FNAME");
        String pass=rs.getString("DOB");
        String pn=rs.getString("QU");
        String jn=rs.getString("O");
        String cs=rs.getString("A");
        String rn=rs.getString("C");
        String cno=rs.getString("CNO");
        String ge=rs.getString("G");
        String ms=rs.getString("S");

        model.addRow(new Object[]
        {sn,un,cn,pass,pn,jn,cs,rn,cno,ge,ms});

        }
}
}}
catch(Exception e)
{
    JOptionPane.showMessageDialog(null,e.getMessage());
}        // TODO add your handling code here:



       }

       // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
se.setText("");
        DefaultTableModel model=(DefaultTableModel)d1.getModel();
{
    int i=model.getRowCount();
while (i>0)
{
model.removeRow(0);
i--;
}

}
try
{
    Class.forName("java.sql.DriverManager");
    Connection c=(Connection)DriverManager.getConnection
            ("jdbc:mysql://localhost:3306/ovs","root","RRMPS");
    Statement S=(Statement)c.createStatement();
        String query="select * from ADHARCARD;";
        ResultSet rs=S.executeQuery(query);
        while(rs.next())
        {


        String sn=rs.getString("ADH");
        String un=rs.getString("NAME");
        String cn=rs.getString("FNAME");
        String pass=rs.getString("DOB");
        String pn=rs.getString("QU");
        String jn=rs.getString("O");
        String cs=rs.getString("A");
        String rn=rs.getString("C");
        String cno=rs.getString("CNO");
        String ge=rs.getString("G");
        String ms=rs.getString("S");

        model.addRow(new Object[]
        {sn,un,cn,pass,pn,jn,cs,rn,cno,ge,ms});

        }
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(null,e.getMessage());
}          // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
se.requestFocus(true);            // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        se.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void seActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adharcardlist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable d1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField se;
    // End of variables declaration//GEN-END:variables

}
