import java.sql.Connection;
       import java.sql.Statement;
       import java.sql.ResultSet;
       import java.sql.DriverManager;/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.JOptionPane;

/*
 * checkregistration.java
 *
 * Created on Oct 9, 2014, 10:33:50 PM
 */

/**
 *
 * @author 1
 */
public class checkregistration extends javax.swing.JFrame {

    /** Creates new form checkregistration */
    public checkregistration() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        but1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        but4 = new javax.swing.JButton();
        but3 = new javax.swing.JButton();
        but2 = new javax.swing.JButton();
        t1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(0);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jLabel1.setText("CHECK REGISTRATION STATUS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 630, -1));

        but1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        but1.setText("SUBMIT");
        but1.setToolTipText("Plzz Click To SUBMIT");
        but1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but1ActionPerformed(evt);
            }
        });
        getContentPane().add(but1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 120, 34));

        jLabel2.setFont(new java.awt.Font("Centaur", 1, 24)); // NOI18N
        jLabel2.setText("Enter Adhar Card No.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        but4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        but4.setText("Back");
        but4.setToolTipText("Plzz Click To SUBMIT");
        but4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but4ActionPerformed(evt);
            }
        });
        getContentPane().add(but4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, 34));

        but3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        but3.setText("Reset");
        but3.setToolTipText("Plzz Click To SUBMIT");
        but3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but3ActionPerformed(evt);
            }
        });
        getContentPane().add(but3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, 34));

        but2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        but2.setText("Exit");
        but2.setToolTipText("Plzz Click To SUBMIT");
        but2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but2ActionPerformed(evt);
            }
        });
        getContentPane().add(but2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, -1, 34));

        t1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        t1.setToolTipText("Enter Your Adhar card No & Then  Click Submit To Check Your Registration.");
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 114, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/article-2305474-19291096000005DC-62_634x286.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_t1ActionPerformed

    private void but1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but1ActionPerformed
int b=Integer.parseInt(t1.getText());
{ try
{
Class.forName("java.sql.DriverManager");
Connection C=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/ovs","root","RRMPS");
Statement S=(Statement)C.createStatement();
Statement S1=(Statement)C.createStatement();
String query="select * from registration WHERE ADHARCARDNO='"+b+"';";
String query2="select * from adharcard where adh='"+b+"';";
ResultSet r =S.executeQuery(query);
ResultSet r1 =S1.executeQuery(query2);
if(r1.first()==false)
{
JOptionPane.showMessageDialog(this,"Adharcard doesn't exist");
}
if(r.first()==false&&r1.first()==true)
{
JOptionPane.showMessageDialog(this,"You Are not registerd");
}
if(r.first()==true&&r1.first()==true)
{
String ni=r.getString("regno");
JOptionPane.showMessageDialog(this,"You Are  Registerd.... your registration no. is "+ ni);
}
}
catch(Exception e)
{
}
}
}//GEN-LAST:event_but1ActionPerformed

    private void but2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but2ActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_but2ActionPerformed

    private void but3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but3ActionPerformed
 t1.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_but3ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
int i=JOptionPane.showConfirmDialog(this,"Do you Want To Exit");
if(i==0)
{this.dispose();}        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
t1.requestFocus(true);            // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void but4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but4ActionPerformed
 this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_but4ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new checkregistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but1;
    private javax.swing.JButton but2;
    private javax.swing.JButton but3;
    private javax.swing.JButton but4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables

}
