import java.sql.Connection;
       import java.sql.Statement;
       import java.sql.ResultSet;
       import java.sql.DriverManager;/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.JOptionPane;

/*
 * deleteregistration.java
 *
 * Created on Sep 6, 2014, 9:44:01 PM
 */

/**
 *
 * @author 1
 */
public class deleteregistration extends javax.swing.JFrame {

    /** Creates new form deleteregistration */
    public deleteregistration() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        but1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        n = new javax.swing.JTextField();
        f = new javax.swing.JTextField();
        qa = new javax.swing.JTextField();
        a = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ci = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        dob = new javax.swing.JTextField();
        co = new javax.swing.JTextField();
        nam = new javax.swing.JTextField();
        ma = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        but = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ad = new javax.swing.JTextArea();
        but4 = new javax.swing.JButton();
        but5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(0);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        jLabel8.setText("DELETE REGISTRATION");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        jLabel17.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 51, 51));
        jLabel17.setText("Enter Registration No.");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        t1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        t1.setToolTipText("Enter Registration No.");
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 190, -1));

        jLabel16.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 51, 51));
        jLabel16.setText("Enter Adharcard no.");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        t2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        t2.setToolTipText("Enter Adharcard No.");
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 190, -1));

        but1.setFont(new java.awt.Font("Simplified Arabic", 1, 24)); // NOI18N
        but1.setText("SUBMIT");
        but1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but1ActionPerformed(evt);
            }
        });
        getContentPane().add(but1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 109, -1, 40));

        jButton4.setFont(new java.awt.Font("Simplified Arabic", 1, 24)); // NOI18N
        jButton4.setText("RESET");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 109, -1, 40));

        jLabel3.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 204));
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel4.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 204));
        jLabel4.setText("Father's Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel5.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 204));
        jLabel5.setText("Qualification");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, -1, -1));

        jLabel6.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 204));
        jLabel6.setText("Gender");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, -1, -1));

        jLabel7.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 204));
        jLabel7.setText("Address");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        n.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        n.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        n.setEnabled(false);
        n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nActionPerformed(evt);
            }
        });
        getContentPane().add(n, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 190, 20));

        f.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        f.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        f.setEnabled(false);
        f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fActionPerformed(evt);
            }
        });
        getContentPane().add(f, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 190, -1));

        qa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        qa.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        qa.setEnabled(false);
        qa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qaActionPerformed(evt);
            }
        });
        getContentPane().add(qa, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 610, 200, -1));

        a.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        a.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        a.setEnabled(false);
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });
        getContentPane().add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 320, 120, -1));

        jLabel9.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 204));
        jLabel9.setText("City");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, -1, -1));

        ci.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ci.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ci.setEnabled(false);
        ci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciActionPerformed(evt);
            }
        });
        getContentPane().add(ci, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 200, -1));

        jLabel13.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 204, 204));
        jLabel13.setText("Marital Status");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, -1, -1));

        jLabel10.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 204, 204));
        jLabel10.setText("Nationality");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, -1, -1));

        jLabel12.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 204, 204));
        jLabel12.setText("Contact No.");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, -1, -1));

        jLabel11.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 204, 204));
        jLabel11.setText("D.O.B");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        dob.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        dob.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        dob.setEnabled(false);
        dob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobActionPerformed(evt);
            }
        });
        getContentPane().add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 200, -1));

        co.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        co.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        co.setEnabled(false);
        co.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coActionPerformed(evt);
            }
        });
        getContentPane().add(co, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 560, 200, -1));

        nam.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nam.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        nam.setEnabled(false);
        nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namActionPerformed(evt);
            }
        });
        getContentPane().add(nam, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 400, 120, -1));

        ma.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ma.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ma.setEnabled(false);
        ma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maActionPerformed(evt);
            }
        });
        getContentPane().add(ma, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 360, 120, -1));

        jLabel15.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 51));
        jLabel15.setText("Registration No.");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, -1, -1));

        jLabel14.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 51));
        jLabel14.setText("Adharcard no.");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, -1, -1));
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 200, 120, 30));
        getContentPane().add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 230, 120, 30));

        but.setFont(new java.awt.Font("Simplified Arabic", 1, 24)); // NOI18N
        but.setText("DELETE");
        but.setEnabled(false);
        but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butActionPerformed(evt);
            }
        });
        getContentPane().add(but, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 580, -1, 40));

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton5.setText("EXIT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 580, 90, 40));

        ad.setEditable(false);
        ad.setColumns(20);
        ad.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ad.setRows(5);
        ad.setToolTipText("Enter Your Address");
        jScrollPane1.setViewportView(ad);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 220, -1));

        but4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        but4.setText("Back");
        but4.setToolTipText("Plzz Click To SUBMIT");
        but4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but4ActionPerformed(evt);
            }
        });
        getContentPane().add(but4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        but5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        but5.setText("Exit");
        but5.setToolTipText("Plzz Click To SUBMIT");
        but5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but5ActionPerformed(evt);
            }
        });
        getContentPane().add(but5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 581, 70, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/marriage-registration.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_fActionPerformed

    private void qaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qaActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_qaActionPerformed

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_aActionPerformed

    private void ciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_ciActionPerformed

    private void dobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_dobActionPerformed

    private void coActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_coActionPerformed

    private void namActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_namActionPerformed

    private void maActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_maActionPerformed

    private void nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_nActionPerformed

    private void but1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but1ActionPerformed

        String ad,na;
ad=t1.getText();
na=t2.getText();

  try
    {
      Class.forName("java.sql.DriverManager");
      Connection C=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/ovs","root","RRMPS");
        Statement S=(Statement)C.createStatement();
        String query="select * from REGISTRATION WHERE REGNO='"+ad+"' and ADHARCARDNO ='"+na+"';";
        ResultSet r =S.executeQuery(query);
if(!r.first())
{
JOptionPane.showMessageDialog(this,"Details Not Found...Specify Correct Details");

}
else            
        {  String ni=r.getString("name");
              String mi=r.getString("fname");
                String o=r.getString("qu");
                  String p=r.getString("ad");
                    String w=r.getString("ci");
                     String x=r.getString("cno");
                      String y=r.getString("na");
                       String z=r.getString("ge");
                        String m=r.getString("ms");
                         String e=r.getString("dob");
                          String ei=r.getString("regno");
                           String ej=r.getString("adharcardno");

                      n.setText(ni);
                      f.setText(mi);

                      qa.setText(o);
                      a.setText(z);
                      this.ad.setText(p);

                      ci.setText(w);
                      dob.setText(e);
                      co.setText(x);
                      nam.setText(y);
                      ma.setText(m);
                         l1.setText(ej);
                            l2.setText(ei);
t1.setEditable(false);
t2.setEditable(false);
but.setEnabled(true);
    }
    }

        catch(Exception e)
        {}        // TODO add your handling code here:
}//GEN-LAST:event_but1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
but.setEnabled(false);
l1.setText("");
l2.setText("");
        n.setText("");
        f.setText("");
        ad.setText("");
        dob.setText("");
        ci.setText("");
        co.setText("");
        qa.setText("");
        a.setText("");
        ma.setText("");
       nam.setText("");
        t1.setText("");
t2.setText("");
t1.setEditable(true);
t2.setEditable(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butActionPerformed

       int k =Integer.parseInt(l2.getText());
        try{
            Class.forName("java.sql.DriverManager");
            Connection c=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/ovs","root","RRMPS");
            Statement s=(Statement)c.createStatement();
            String q="delete from registration where regno =" + k +";";
            s.executeUpdate(q);
            JOptionPane.showMessageDialog(this,"Registration deleted","deleted",1);

            n.setText("");
        f.setText("");
        ad.setText("");
        dob.setText("");
        ci.setText("");
        co.setText("");
        qa.setText("");
        a.setText("");
        ma.setText("");
       nam.setText("");
        t2.setText("");
        t1.setText("");
        t1.setEnabled(true);
        t2.setEnabled(true);
but.setEnabled(false);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this,"Registration Not deleted","Error",0);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_butActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        System.exit(0);    // TODO add your handling code here:
}//GEN-LAST:event_jButton5ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
int i=JOptionPane.showConfirmDialog(this,"Do you Want To Exit");
if(i==0)
{System.exit(0);}        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
t2.requestFocus(true);            // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void but4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but4ActionPerformed
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_but4ActionPerformed

    private void but5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but5ActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_but5ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new deleteregistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a;
    private javax.swing.JTextArea ad;
    private javax.swing.JButton but;
    private javax.swing.JButton but1;
    private javax.swing.JButton but4;
    private javax.swing.JButton but5;
    private javax.swing.JTextField ci;
    private javax.swing.JTextField co;
    private javax.swing.JTextField dob;
    private javax.swing.JTextField f;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JTextField ma;
    private javax.swing.JTextField n;
    private javax.swing.JTextField nam;
    private javax.swing.JTextField qa;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    // End of variables declaration//GEN-END:variables

}
