import java.sql.Connection;
       import java.sql.Statement;
       import java.sql.ResultSet;
       import java.sql.DriverManager;/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import java.text.SimpleDateFormat;
import java.util.Calendar;

import java.util.Date;
import javax.swing.JOptionPane;

/*
 * NEWREGISTRATION.java
 *
 * Created on Jul 18, 2014, 9:56:46 PM
 */

/**
 *
 * @author 1
 */
public class NEWREGISTRATION extends javax.swing.JFrame {

    /** Creates new form NEWREGISTRATION */
    public NEWREGISTRATION() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        but1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        n = new javax.swing.JTextField();
        f = new javax.swing.JTextField();
        q = new javax.swing.JTextField();
        c = new javax.swing.JTextField();
        co = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        a = new javax.swing.JTextArea();
        but = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        na1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        d1 = new datechooser.beans.DateChooserCombo();
        jLabel14 = new javax.swing.JLabel();
        L1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(0);
        setTitle("NEW REGISTRATION");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 36)); // NOI18N
        jLabel1.setText("NEW REGISTRATION");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Centaur", 1, 24)); // NOI18N
        jLabel2.setText("Insert Adhar Card No.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        t1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        t1.setToolTipText("Enter Your Adhar Card No. & Select Your DOB & Click Submit.");
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 150, -1));

        but1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        but1.setText("SUBMIT");
        but1.setToolTipText("Plzz Click To SUBMIT");
        but1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but1ActionPerformed(evt);
            }
        });
        getContentPane().add(but1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Centaur", 1, 24)); // NOI18N
        jLabel3.setText("Date Of Birth");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        jLabel4.setText("NAME");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        jLabel5.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        jLabel5.setText("F.NAME");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        jLabel11.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        jLabel11.setText("QUALIFICATION");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 580, -1, -1));

        jLabel6.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        jLabel6.setText("ADDRESS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, -1));

        jLabel10.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        jLabel10.setText("CITY");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, -1, -1));

        jLabel9.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        jLabel9.setText("CONTACT NO.");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, -1, -1));

        jLabel8.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        jLabel8.setText("GENDER");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 330, -1, -1));

        jLabel12.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        jLabel12.setText("MARITAL SATUS");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 430, -1, -1));

        t2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        t2.setEnabled(false);
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 340, 100, -1));

        t3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        t3.setEnabled(false);
        getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 440, 140, -1));

        n.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        n.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        n.setEnabled(false);
        n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nActionPerformed(evt);
            }
        });
        getContentPane().add(n, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 180, -1));

        f.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        f.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        f.setEnabled(false);
        getContentPane().add(f, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 180, -1));

        q.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        q.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        q.setEnabled(false);
        getContentPane().add(q, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 580, 180, -1));

        c.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        c.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        c.setEnabled(false);
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });
        getContentPane().add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, 180, -1));

        co.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        co.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        co.setEnabled(false);
        getContentPane().add(co, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 540, 180, -1));

        a.setBackground(new java.awt.Color(204, 204, 204));
        a.setColumns(20);
        a.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        a.setRows(5);
        a.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        a.setEnabled(false);
        jScrollPane1.setViewportView(a);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, -1, -1));

        but.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        but.setText("REGISTER");
        but.setEnabled(false);
        but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butActionPerformed(evt);
            }
        });
        getContentPane().add(but, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 530, -1, -1));

        jLabel13.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        jLabel13.setText("NATIONALITY");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, -1, -1));

        na1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        na1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        na1.setEnabled(false);
        getContentPane().add(na1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 380, 120, -1));

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setText("CLEAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 140, -1, -1));

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton4.setText("EXIT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 650, -1, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 650, -1, -1));

        d1.setFieldFont(new java.awt.Font("Times New Roman", java.awt.Font.BOLD, 14));
        getContentPane().add(d1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, -1, -1));

        jLabel14.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        jLabel14.setText("ADHARCARD NO.");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 300, -1, -1));
        getContentPane().add(L1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 300, 110, 20));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paper-notes-vector8.jpg"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_t1ActionPerformed

    private void but1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but1ActionPerformed
String ad;
ad=t1.getText();
Calendar D=d1.getSelectedDate();
String dob=D.get(D.DATE)+"-"+(D.get(D.MONTH)+1)+"-"+D.get(D.YEAR);
{ try
{
Class.forName("java.sql.DriverManager");
Connection C=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/ovs","root","RRMPS");
Statement S=(Statement)C.createStatement();
String query="select * from ADHARCARD WHERE ADH='"+ad+"' and DOB='"+dob+"';";
ResultSet r =S.executeQuery(query);
if(r.first()==false)//if details are not found
{
JOptionPane.showMessageDialog(this,"Details Not Found...Specify Correct Details");
}
else
{
{
String ni=r.getString("name");
String mi=r.getString("fname");
String o=r.getString("qu");
String p=r.getString("a");
String w=r.getString("c");
String yi=r.getString("cno");
String u=r.getString("g");
String v=r.getString("s");
String na=r.getString("NA");
String date=r.getString("DOB");
n.setText(ni); 
f.setText(mi);
q.setText(o);
a.setText(p);
c.setText(w);
co.setText(yi);
na1.setText(na);
but.setEnabled(true);
L1.setText(ad);
t2.setText(u); 
t3.setText(v);
} }  }
catch(Exception e)
{ } }
}//GEN-LAST:event_but1ActionPerformed

    private void nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nActionPerformed

    private void butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butActionPerformed
int b=Integer.parseInt(L1.getText());
Calendar ef=d1.getSelectedDate();
String dob1=ef.get(ef.DATE)+"-"+(ef.get(ef.MONTH)+1)+"-"+ef.get(ef.YEAR);
int y=ef.get(ef.YEAR);
if(y<=1997)
{
{try
{
Class.forName("java.sql.DriverManager");
Connection CA=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/ovs","root","RRMPS");
Statement SA=(Statement)CA.createStatement();
String query="select * from registration WHERE ADHARCARDNO='"+b+"';";
ResultSet r =SA.executeQuery(query);
if(r.first()==false)
{
but1.setEnabled(false);
but.setEnabled(false);
String N=n.getText();
String fname=f.getText();
Calendar D=d1.getSelectedDate();
String dob=D.get(D.DATE)+"-"+(D.get(D.MONTH)+1)+"-"+D.get(D.YEAR);//getting date
long reg;
String qu=q.getText();
String ad=a.getText();
String ci=c.getText();
String ge=t2.getText();
String na=na1.getText();
String ms=t3.getText();
String cno=co.getText();
String adha=L1.getText();
{ try
{
Class.forName("java.sql.DriverManager");
Connection C=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/OVS","root","RRMPS");
Statement S=(Statement)C.createStatement();
String query3="select max(regno) from REGISTRATION;";
ResultSet rS =S.executeQuery(query3);
rS.next();
 int acc=Integer.parseInt(rS.getString("max(regno)"));
                reg=acc+1;


String A="Insert Into REGISTRATION values('"+reg+"','"+N+"','"+fname+"','"+qu+"','"+ad+"','"+ci+"','"+cno+"','"+na+"','"+ge+"','"+ms+"','"+dob+"','"+adha+"');";
S.executeUpdate(A);
JOptionPane.showMessageDialog(null,"Registration Successfull!!!!"+"\n Registration no. is "+reg);
}
catch(Exception e){JOptionPane.showMessageDialog(this,e.getMessage());}
}   }
else if(r.first()==true)
{
String ni=r.getString("regno");
JOptionPane.showMessageDialog(this,"You Are  Registerd.... your registration no. is "+ ni);
}
// TODO add your handling code here:
 }
catch(Exception ec){
         JOptionPane.showMessageDialog(this,ec.getMessage());}
}
}
else
JOptionPane.showMessageDialog(this,"Sorry,You are not elgible to vote!!!! i.e. under 18 years ");
}//GEN-LAST:event_butActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
System.exit(0);   // TODO add your handling code here:
}//GEN-LAST:event_jButton4ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
but1.setEnabled(true);
t1.setText("");
n.setText("");
f.setText("");
q.setText("");
a.setText("");
c.setText("");
co.setText("");
na1.setText("");
t2.setText("");       
t3.setText("");
}//GEN-LAST:event_jButton3ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.setVisible(false) ;
// TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
int i=JOptionPane.showConfirmDialog(this,"Do you Want To Exit");
if(i==0)
{this.dispose();}    // TODO add your handling code here:
}//GEN-LAST:event_formWindowClosing

private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_cActionPerformed

private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
t1.requestFocus(true);        // TODO add your handling code here:
}//GEN-LAST:event_formWindowActivated

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NEWREGISTRATION().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L1;
    private javax.swing.JTextArea a;
    private javax.swing.JButton but;
    private javax.swing.JButton but1;
    private javax.swing.JTextField c;
    private javax.swing.JTextField co;
    private datechooser.beans.DateChooserCombo d1;
    private javax.swing.JTextField f;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField n;
    private javax.swing.JTextField na1;
    private javax.swing.JTextField q;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    // End of variables declaration//GEN-END:variables

}
