
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UPDATEADHARCARD.java
 *
 * Created on Aug 19, 2014, 10:00:44 PM
 */

/**
 *
 * @author 1
 */
public class UPDATEADHARCARD extends javax.swing.JFrame {

    /** Creates new form UPDATEADHARCARD */
    public UPDATEADHARCARD() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fn = new javax.swing.JTextField();
        qua = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ad = new javax.swing.JTextArea();
        dy = new datechooser.beans.DateChooserCombo();
        cn = new javax.swing.JTextField();
        oc = new javax.swing.JTextField();
        ci = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        ma = new javax.swing.JRadioButton();
        fem = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        m1 = new javax.swing.JRadioButton();
        m2 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        ot = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        ots = new javax.swing.JRadioButton();
        in = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        B1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        T1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        k = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        n = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(0);
        setTitle("UPDATE ADHAAR CARD");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        jLabel12.setText("OCCUPATION");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, -1, -1));

        jLabel11.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        jLabel11.setText("QUALIFICATION");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, -1, -1));

        jLabel6.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        jLabel6.setText("ADDRESS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));

        jLabel10.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        jLabel10.setText("CITY");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, -1, -1));

        jLabel4.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        jLabel4.setText("D.O.B");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));

        jLabel3.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        jLabel3.setText("NAME");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        jLabel2.setText("F.NAME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        jLabel9.setFont(new java.awt.Font("Simplified Arabic", 1, 18)); // NOI18N
        jLabel9.setText("CONTACT NO.");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, -1, -1));

        fn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        fn.setToolTipText("Enter Your Fathers Name");
        fn.setEnabled(false);
        fn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnActionPerformed(evt);
            }
        });
        getContentPane().add(fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 190, -1));

        qua.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        qua.setToolTipText("Enter your Qualification");
        qua.setEnabled(false);
        qua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quaActionPerformed(evt);
            }
        });
        getContentPane().add(qua, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 540, 180, -1));

        ad.setColumns(20);
        ad.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ad.setRows(5);
        ad.setToolTipText("Enter Your Address");
        ad.setEnabled(false);
        jScrollPane1.setViewportView(ad);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, -1, -1));

        dy.setEnabled(false);
        dy.setFieldFont(new java.awt.Font("Times New Roman", java.awt.Font.BOLD, 14));
        getContentPane().add(dy, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, -1, -1));

        cn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cn.setToolTipText("Enter Your Contact No.");
        cn.setEnabled(false);
        cn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnActionPerformed(evt);
            }
        });
        getContentPane().add(cn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 180, -1));

        oc.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        oc.setToolTipText("Enter your Occupation");
        oc.setEnabled(false);
        oc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ocActionPerformed(evt);
            }
        });
        getContentPane().add(oc, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, 180, -1));

        ci.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ci.setToolTipText("Enter Your City You Belong");
        ci.setEnabled(false);
        ci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciActionPerformed(evt);
            }
        });
        getContentPane().add(ci, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 180, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GENDER", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Simplified Arabic Fixed", 1, 18))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jPanel2.setName("GENDER"); // NOI18N
        jPanel2.setOpaque(false);

        ma.setBackground(new java.awt.Color(102, 255, 0));
        buttonGroup1.add(ma);
        ma.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        ma.setText("MALE");
        ma.setToolTipText("Select Your Gender.");
        ma.setEnabled(false);
        ma.setOpaque(false);

        fem.setBackground(new java.awt.Color(102, 255, 0));
        buttonGroup1.add(fem);
        fem.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        fem.setText("FEMALE");
        fem.setToolTipText("Select Your Gender.");
        fem.setEnabled(false);
        fem.setOpaque(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ma)
                    .addComponent(fem))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(ma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MARITAL STATUS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Simplified Arabic Fixed", 1, 18))); // NOI18N
        jPanel3.setOpaque(false);

        buttonGroup2.add(m1);
        m1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        m1.setText("MARRIED");
        m1.setToolTipText("Select Your Martial Status.");
        m1.setEnabled(false);
        m1.setOpaque(false);

        buttonGroup2.add(m2);
        m2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        m2.setText("UN MARRIED");
        m2.setToolTipText("Select Your Martial Status.");
        m2.setEnabled(false);
        m2.setOpaque(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(m2)
                    .addComponent(m1))
                .addGap(89, 89, 89))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(m1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(m2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, -1, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NATIONALITY", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Simplified Arabic", 1, 18))); // NOI18N
        jPanel4.setOpaque(false);

        ot.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        ot.setToolTipText("Specify Your Country You Belong.");
        ot.setEnabled(false);
        ot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel14.setText("(SPECIFY)");
        jLabel14.setEnabled(false);

        buttonGroup3.add(ots);
        ots.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        ots.setText("OTHER");
        ots.setToolTipText("Select Your Nationality.");
        ots.setEnabled(false);
        ots.setOpaque(false);
        ots.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otsActionPerformed(evt);
            }
        });
        ots.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                otsKeyPressed(evt);
            }
        });

        buttonGroup3.add(in);
        in.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        in.setText("INDIAN");
        in.setToolTipText("Select Your Nationality.");
        in.setEnabled(false);
        in.setOpaque(false);
        in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(ot, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(ots)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14))
                    .addComponent(in))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(in)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ots)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(ot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, 200, 150));

        jButton2.setFont(new java.awt.Font("Simplified Arabic", 1, 24)); // NOI18N
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 570, -1, 30));

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setText("EXIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 570, -1, -1));

        jLabel1.setFont(new java.awt.Font("Simplified Arabic", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("UPDATE ADHAAR CARD FORM");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setText("Log Out");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 60, -1, -1));

        B1.setFont(new java.awt.Font("Simplified Arabic", 1, 24)); // NOI18N
        B1.setText("UPDATE");
        B1.setToolTipText("CLICK TO SUBMIT");
        B1.setEnabled(false);
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });
        getContentPane().add(B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 569, -1, 30));

        jLabel5.setText("Enter Adhar Card No.");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, -1));

        T1.setToolTipText("Enter your Adhaar Card No.");
        T1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T1ActionPerformed(evt);
            }
        });
        getContentPane().add(T1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 140, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setText("SHOW");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, -1, -1));

        k.setEditable(false);
        k.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        k.setToolTipText("Type Your Fathers Name");
        k.setEnabled(false);
        getContentPane().add(k, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 190, -1));

        jLabel7.setText("(For Display Only)");
        jLabel7.setEnabled(false);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, -1, -1));

        n.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        n.setToolTipText("Enter Your Name");
        n.setEnabled(false);
        n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nActionPerformed(evt);
            }
        });
        getContentPane().add(n, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 190, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paper-notes-vector81.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_cnActionPerformed

    private void nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_nActionPerformed

    private void ciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_ciActionPerformed

    private void inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inActionPerformed
ot.setText("");
ot.setEnabled(false);
        // TODO add your handling code here:
}//GEN-LAST:event_inActionPerformed

    private void otsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otsActionPerformed
ot.setEnabled(true);      // TODO add your handling code here:
}//GEN-LAST:event_otsActionPerformed

    private void otsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_otsKeyPressed
        // TODO add your handling code here:
}//GEN-LAST:event_otsKeyPressed

    private void otActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_otActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
k.setText("");
T1.setText("");
n.setEnabled(false);
fn.setEnabled(false);
qua.setEnabled(false);
dy.setEnabled(false); 
oc.setEnabled(false); 
ad.setEnabled(false); 
T1.setEnabled(true);  
ci.setEnabled(false);
cn.setEnabled(false);
ma.setEnabled(false);
fem.setEnabled(false);
in.setEnabled(false);
ots.setEnabled(false);
ot.setEnabled(false);
m1.setEnabled(false);
m2.setEnabled(false);
dy.setSelectedDate(null);
buttonGroup1.clearSelection();
buttonGroup2.clearSelection();
buttonGroup3.clearSelection();
n.setText("");
fn.setText("");
qua.setText("");
oc.setText("");
ad.setText("");
ci.setText("");
cn.setText("");
ot.setText("");
ot.setEnabled(false);
B1.setEnabled(false);
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       System.exit(0);     // TODO add your handling code here:
}//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setVisible(false);
        new Password().setVisible(true);
                 // TODO add your handling code here:
}//GEN-LAST:event_jButton4ActionPerformed

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
Object q12=T1.getText();
Object q1=n.getText();
Object q2=fn.getText();
Calendar D=dy.getSelectedDate();
Object q4=qua.getText();
Object q5=oc.getText();
Object q8=ad.getText();
Object q6=ci.getText();
Object q7=cn.getText();
String g=null;
String s=null;
long adh;
String na=null;
if (ma.isSelected()==true)
{
g="Male";
}
else if(fem.isSelected() == true)
{
g="Female";
}
if (m1.isSelected()==true)
{
s="Married";
}
else if(m2.isSelected() == true)
{
s="Unmarried";
}
if (in.isSelected()==true)
{
na="Indian";
}
else if (ots.isSelected()==true)
{
na=ot.getText();
}
String cno=cn.getText();
if (n.getText().equals(""))
{
JOptionPane.showMessageDialog(this,"Please fill Name.....");
}
else if (fn.getText().equals(""))
{
JOptionPane.showMessageDialog(this,"Please fill Father's Name.....");
}
else if (qua.getText().equals(""))
{
JOptionPane.showMessageDialog(this,"Please fill Qualification......");
}
else if (oc.getText().equals(""))
{
JOptionPane.showMessageDialog(this,"Please fill Occupation......");
}
else if (ad.getText().equals(""))
{
JOptionPane.showMessageDialog(this,"Please fill Addresss.....");
}
else if (ci.getText().equals(""))
{
JOptionPane.showMessageDialog(this,"Please fill City Name.....");
}
else if (cn.getText().equals(""))
{
JOptionPane.showMessageDialog(this,"Please fill Contact no.....");
}
else if (ma.isSelected()==false && fem.isSelected()==false)
{
JOptionPane.showMessageDialog(this,"Please Select Gender.....");
}
else if (m1.isSelected()==false && m2.isSelected()==false)
{
JOptionPane.showMessageDialog(this,"Please Select Marital Status.....");
}
else if ((in.isSelected()==false && ots.isSelected()==false )||(ots.isSelected()==true && ot.getText().equals("")))
{
JOptionPane.showMessageDialog(this,"Please Specify Nationality.....");
}
else if(D==null)
{
JOptionPane.showMessageDialog(this,"Please enter your Date of Birth again for Reconfirmation");
}
else {
String dob=D.get(D.DATE)+"-"+(D.get(D.MONTH)+1)+"-"+D.get(D.YEAR);

try {
Class.forName("java.sql.DriverManager");
Connection C=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/OVS","root","RRMPS");
Statement S=(Statement)C.createStatement();
String query="update adharcard  set  NAME='"+q1+"',FNAME='"+q2+"',G='"+g+"',S='"+s+"',QU='"+q4+"',O='"+q5+"',A='"+q8+"',C='"+q6+"',NA='"+na+"',CNO='"+q7+"',DOB='"+dob+"' Where ADH='"+q12+"';";
S.executeUpdate(query);
JOptionPane.showMessageDialog(null,"UPDATION SUCCESSFULL.....!!!!");
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(this,e.getMessage());
}
T1.setEnabled(false);
n.setEnabled(false);
fn.setEnabled(false);
qua.setEnabled(false);
dy.setEnabled(false);
oc.setEnabled(false);
ad.setEnabled(false);
ci.setEnabled(false);
cn.setEnabled(false);
ma.setEnabled(false);
fem.setEnabled(false);
in.setEnabled(false);
ots.setEnabled(false);
ot.setEnabled(false);
m1.setEnabled(false);
m2.setEnabled(false);
}
}//GEN-LAST:event_B1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
dy.setSelectedDate(null);
buttonGroup1.clearSelection();
buttonGroup2.clearSelection();
buttonGroup3.clearSelection();
Object q=T1.getText();
{
    try
{
Class.forName("java.sql.DriverManager");
Connection C=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/OVS","root","RRMPS");
Statement S=(Statement)C.createStatement();
String query="select * from ADHARCARD WHERE ADH='"+q+"';";
ResultSet r =S.executeQuery(query);
if (r.first()==false)
{
JOptionPane.showMessageDialog(this,"Enter correct Adhar Card No.....");
B1.setEnabled(false);
T1.setEnabled(true);
n.setEnabled(false);
fn.setEnabled(false);
qua.setEnabled(false);
dy.setEnabled(false);
oc.setEnabled(false);
ad.setEnabled(false);
ci.setEnabled(false);
cn.setEnabled(false);
ma.setEnabled(false);
fem.setEnabled(false);
in.setEnabled(false);
ots.setEnabled(false);
ot.setEnabled(false);
m1.setEnabled(false);
m2.setEnabled(false);
}
else
{   
{
String ni=r.getString("name");
String mi=r.getString("fname");
String o=r.getString("qu");
String p=r.getString("a");
String w=r.getString("c");
String yi=r.getString("cno");
String u=r.getString("g");
String v=r.getString("s");
String na=r.getString("NA");
String occu=r.getString("O");
String DOB1=r.getString("DOB");
n.setText(ni);
fn.setText(mi);
qua.setText(o);
oc.setText(occu);
ad.setText(p);
ci.setText(w);
k.setText(DOB1);
cn.setText(yi);
if(u.equalsIgnoreCase("male"))
{
ma.setSelected(true);
}
else if(u.equalsIgnoreCase("female"))
{
fem.setSelected(true);
}
if(v.equalsIgnoreCase("married"))
{
m1.setSelected(true);
}
else if(v.equalsIgnoreCase("unmarried"))
{
m2.setSelected(true);
}
if(na.equalsIgnoreCase("Indian"))
{
in.setSelected(true);
}
else
{
ot.setEnabled(true);
ots.setSelected(true);
ot.setText(na);
}
in.setEnabled(true);
k.setEnabled(true);
n.setEnabled(true);
fn.setEnabled(true);
qua.setEnabled(true);
dy.setEnabled(true);
oc.setEnabled(true);
ad.setEnabled(true);
ci.setEnabled(true);
cn.setEnabled(true);
ma.setEnabled(true);
fem.setEnabled(true);
n.setEnabled(true);
ots.setEnabled(true);
m1.setEnabled(true);
m2.setEnabled(true);
B1.setEnabled(true);
}    } }
catch(Exception e)
{  

}
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
int i=JOptionPane.showConfirmDialog(this,"Do you Want To Exit");
if(i==0)
{System.exit(0);}        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void fnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnActionPerformed

    private void quaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quaActionPerformed

    private void ocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ocActionPerformed

    private void T1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
T1.requestFocus(true);            // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UPDATEADHARCARD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B1;
    private javax.swing.JTextField T1;
    private javax.swing.JTextArea ad;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JTextField ci;
    private javax.swing.JTextField cn;
    private datechooser.beans.DateChooserCombo dy;
    private javax.swing.JRadioButton fem;
    private javax.swing.JTextField fn;
    private javax.swing.JRadioButton in;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField k;
    private javax.swing.JRadioButton m1;
    private javax.swing.JRadioButton m2;
    private javax.swing.JRadioButton ma;
    private javax.swing.JTextField n;
    private javax.swing.JTextField oc;
    private javax.swing.JTextField ot;
    private javax.swing.JRadioButton ots;
    private javax.swing.JTextField qua;
    // End of variables declaration//GEN-END:variables

}
