import java.sql.Connection;
       import java.sql.Statement;
       import java.sql.ResultSet;
       import java.sql.DriverManager;/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.JOptionPane;

/*
 * VoteLogin.java
 *
 * Created on Oct 12, 2014, 8:52:51 PM
 */

/**
 *
 * @author 1
 */
public class VoteLogin extends javax.swing.JFrame {

    /** Creates new form VoteLogin */
    public VoteLogin() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        t1 = new javax.swing.JTextField();
        but3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        but1 = new javax.swing.JButton();
        but2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(0);
        setTitle("VOTE LOGIN");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        t2.setToolTipText("Enter Your Registration No & Then Click Login To Caste Vote.");
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 140, -1));

        jLabel3.setFont(new java.awt.Font("Centaur", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Enter Registration no.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        jButton5.setFont(new java.awt.Font("Andalus", 1, 20)); // NOI18N
        jButton5.setText("EXIT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, -1, 40));

        t1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        t1.setToolTipText("Enter Your Adhar Card No.");
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 140, -1));

        but3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        but3.setText("BACK");
        but3.setToolTipText("Plzz Click To SUBMIT");
        but3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but3ActionPerformed(evt);
            }
        });
        getContentPane().add(but3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, 40));

        jLabel2.setFont(new java.awt.Font("Centaur", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Enter Adharcard no.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        but1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        but1.setText("LOGIN");
        but1.setToolTipText("Plzz Click To SUBMIT");
        but1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but1ActionPerformed(evt);
            }
        });
        getContentPane().add(but1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        but2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        but2.setText("RESET");
        but2.setToolTipText("Plzz Click To SUBMIT");
        but2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but2ActionPerformed(evt);
            }
        });
        getContentPane().add(but2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, -1, 30));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("ONLINE VOTING");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/article-2305474-19291096000005DC-62_634x286.jpg"))); // NOI18N
        jLabel4.setMaximumSize(new java.awt.Dimension(950, 622));
        jLabel4.setMinimumSize(new java.awt.Dimension(950, 622));
        jLabel4.setPreferredSize(new java.awt.Dimension(950, 622));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_t1ActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void but1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but1ActionPerformed
{ try
{
if(t1.getText().equals(""))
{
JOptionPane.showMessageDialog(this,"Please fill Adhar card no","",0);
}
else if(t2.getText().equals(""))
{
JOptionPane.showMessageDialog(this,"Please fill Registration no","",0);
}
else{
long ad,am;
ad=Long.parseLong(t1.getText());
am=Long.parseLong(t2.getText());
Class.forName("java.sql.DriverManager");
Connection C=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/ovs","root","RRMPS");
Statement S=(Statement)C.createStatement();
Statement Sa=(Statement)C.createStatement();
Statement Sb=(Statement)C.createStatement();
{String query="select * from REGISTRATION WHERE ADHarcardno='"+ad+"'and regno='"+am+"' ;";
ResultSet r =S.executeQuery(query);
if(r.first()==false) {
JOptionPane.showMessageDialog(this,"Details Not Found...Specify Correct Details");
}
else {String query2="select * from VOTELIST WHERE ADHarcardno='"+ad+"'and REGISTRATION='"+am+"' ;";
ResultSet rs =S.executeQuery(query2);
if(rs.next()==false){
String query1="Insert Into VOTELIST values('"+ad+"','"+am+"');";
Sa.executeUpdate(query1);
JOptionPane.showMessageDialog(this,"Welcome!!!!!!!!!!");
new EVM().setVisible(true);
}
else
{JOptionPane.showMessageDialog(this,"You Have Already Voted.\n You Cannot give more than one Vote!!","Warning",0);
}
}
  }}}
catch(Exception e) {
    JOptionPane.showMessageDialog(this, e.getMessage());
}}


        // TODO add your handling code here:
}//GEN-LAST:event_but1ActionPerformed

    private void but2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but2ActionPerformed
t1.setText("");
t2.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_but2ActionPerformed

    private void but3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but3ActionPerformed
this.dispose();      // TODO add your handling code here:
    }//GEN-LAST:event_but3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
int i=JOptionPane.showConfirmDialog(this,"Do you Want To Exit");
if(i==0)
{this.dispose();}        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
t2.requestFocus(true);            // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VoteLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but1;
    private javax.swing.JButton but2;
    private javax.swing.JButton but3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    // End of variables declaration//GEN-END:variables

}
