
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VOTINGPAD.java
 *
 * Created on Aug 21, 2014, 10:51:50 PM
 */

/**
 *
 * @author 1
 */
public class VOTINGPAD extends javax.swing.JFrame {

    /** Creates new form VOTINGPAD */
    public VOTINGPAD() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(0);
        setTitle("VOTING PAD");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Untitled8.png"))); // NOI18N
        jButton1.setText("\n");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 630, 70, 50));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Untitled8.png"))); // NOI18N
        jButton2.setText(" ");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 230, 70, 60));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Untitled8.png"))); // NOI18N
        jButton3.setText("\n");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 290, 70, 60));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Untitled8.png"))); // NOI18N
        jButton4.setText("\n");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 350, 70, 60));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Untitled8.png"))); // NOI18N
        jButton5.setText("\n");
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 420, 70, 60));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Untitled8.png"))); // NOI18N
        jButton6.setText("\n");
        jButton6.setBorder(null);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 490, 70, 60));

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Untitled8.png"))); // NOI18N
        jButton7.setText("\n");
        jButton7.setBorder(null);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 570, 70, 60));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Click on RED button of your party to vote");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 170, 260, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("NOTE : Vote can not be undone once cast  ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 270, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Untitled13.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String a="BHARTIYA JANTA PARTY";
        try
{
int n=JOptionPane.showConfirmDialog(this,"Are you sure to Vote "+a);
if(n==0)
{
Class.forName("java.sql.DriverManager");
Connection C=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/OVS","root","RRMPS");
Statement S=(Statement)C.createStatement();
String query="select * from VOTINGPAD WHERE PARTYNAME='"+a+"';";
ResultSet r =S.executeQuery(query);
r.next();
String b=r.getString("VOTE");
int c=Integer.parseInt(b);
int d=c+1;
Statement Sa=(Statement)C.createStatement();
String query1="update VotingPad set Vote='"+d+"' Where PARTYNAME='"+a+"';";
Sa.executeUpdate(query1);
JOptionPane.showMessageDialog(this,"Thanks! for Voting....Now you can not undo your vote","Thanks",1);
JOptionPane.showMessageDialog(this,"Now please give your precious time for giving feedback of our application ONLINE VOTING MACHINE","REQUEST",1);
{new feedback().setVisible(true);}
this.dispose();
}
}
catch(Exception e)
{
JOptionPane.showMessageDialog(this,"SORRY");
}

// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
String a="INDIAN NATIONAL CONGRESS";
        try
{
int n=JOptionPane.showConfirmDialog(this,"Are you sure to Vote "+a);
if(n==0)
{
Class.forName("java.sql.DriverManager");
Connection C=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/OVS","root","RRMPS");
Statement S=(Statement)C.createStatement();
String query="select * from VOTINGPAD WHERE PARTYNAME='"+a+"';";
ResultSet r =S.executeQuery(query);
r.next();
String b=r.getString("VOTE");
long c=Long.parseLong(b);
long d=c+1;
Statement Sa=(Statement)C.createStatement();
String query1="update VotingPad set Vote='"+d+"' Where PARTYNAME='"+a+"';";
Sa.executeUpdate(query1);
JOptionPane.showMessageDialog(this,"Thanks! for Voting....Now you can not undo your vote","Thanks",1);
JOptionPane.showMessageDialog(this,"Now please give your precious time for giving feedback of our application ONLINE VOTING MACHINE","REQUEST",1);
{new feedback().setVisible(true);}

this.dispose();}
}
catch(Exception e)
{
JOptionPane.showMessageDialog(this,"SORRY");
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
String a="BAHUJAN SAMAJ PARTY";
        try
{
int n=JOptionPane.showConfirmDialog(this,"Are you sure to Vote "+a);
if(n==0)
{
Class.forName("java.sql.DriverManager");
Connection C=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/OVS","root","RRMPS");
Statement S=(Statement)C.createStatement();
String query="select * from VOTINGPAD WHERE PARTYNAME='"+a+"';";
ResultSet r =S.executeQuery(query);
r.next();
String b=r.getString("VOTE");
long c=Long.parseLong(b);
long d=c+1;
Statement Sa=(Statement)C.createStatement();
String query1="update VotingPad set Vote='"+d+"' Where PARTYNAME='"+a+"';";
Sa.executeUpdate(query1);
JOptionPane.showMessageDialog(this,"Thanks! for Voting....Now you can not undo your vote","Thanks",1);
JOptionPane.showMessageDialog(this,"Now please give your precious time for giving feedback of our application ONLINE VOTING MACHINE","REQUEST",1);
{new feedback().setVisible(true);}

this.dispose();}
}
catch(Exception e)
{
JOptionPane.showMessageDialog(this,"SORRY");
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
String a="COMMUNIST PARTY OF INDIA";
        try
{
int n=JOptionPane.showConfirmDialog(this,"Are you sure to Vote "+a);
if(n==0)
{
Class.forName("java.sql.DriverManager");
Connection C=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/OVS","root","RRMPS");
Statement S=(Statement)C.createStatement();
String query="select * from VOTINGPAD WHERE PARTYNAME='"+a+"';";
ResultSet r =S.executeQuery(query);
r.next();
String b=r.getString("VOTE");
long c=Long.parseLong(b);
long d=c+1;
Statement Sa=(Statement)C.createStatement();
String query1="update VotingPad set Vote='"+d+"' Where PARTYNAME='"+a+"';";
Sa.executeUpdate(query1);
JOptionPane.showMessageDialog(this,"Thanks! for Voting....Now you can not undo your vote","Thanks",1);
JOptionPane.showMessageDialog(this,"Now please give your precious time for giving feedback of our application ONLINE VOTING MACHINE","REQUEST",1);
{new feedback().setVisible(true);}
this.dispose();}
}
catch(Exception e)
{
JOptionPane.showMessageDialog(this,"SORRY");
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
String a="COMMUNIST PARTY OF INDIA MARXIST";
        try
{
int n=JOptionPane.showConfirmDialog(this,"Are you sure to Vote "+a);
if(n==0)
{
Class.forName("java.sql.DriverManager");
Connection C=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/OVS","root","RRMPS");
Statement S=(Statement)C.createStatement();
String query="select * from VOTINGPAD WHERE PARTYNAME='"+a+"';";
ResultSet r =S.executeQuery(query);
r.next();
String b=r.getString("VOTE");
long c=Long.parseLong(b);
long d=c+1;
Statement Sa=(Statement)C.createStatement();
String query1="update VotingPad set Vote='"+d+"' Where PARTYNAME='"+a+"';";
Sa.executeUpdate(query1);
JOptionPane.showMessageDialog(this,"Thanks! for Voting....Now you can not undo your vote","Thanks",1);
JOptionPane.showMessageDialog(this,"Now please give your precious time for giving feedback of our application ONLINE VOTING MACHINE","REQUEST",1);
{new feedback().setVisible(true);}
this.dispose();}
}
catch(Exception e)
{
JOptionPane.showMessageDialog(this,"SORRY");
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
String a="NATIONALIST CONGRESS PARTY";
        try
{
int n=JOptionPane.showConfirmDialog(this,"Are you sure to Vote "+a);
if(n==0)
{
Class.forName("java.sql.DriverManager");
Connection C=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/OVS","root","RRMPS");
Statement S=(Statement)C.createStatement();
String query="select * from VOTINGPAD WHERE PARTYNAME='"+a+"';";
ResultSet r =S.executeQuery(query);
r.next();
String b=r.getString("VOTE");
long c=Long.parseLong(b);
long d=c+1;
Statement Sa=(Statement)C.createStatement();
String query1="update VotingPad set Vote='"+d+"' Where PARTYNAME='"+a+"';";
Sa.executeUpdate(query1);
JOptionPane.showMessageDialog(this,"Thanks! for Voting....Now you can not undo your vote","Thanks",1);
JOptionPane.showMessageDialog(this,"Now please give your precious time for giving feedback of our application ONLINE VOTING MACHINE","REQUEST",1);
{new feedback().setVisible(true);}
this.dispose();}
}
catch(Exception e)
{
JOptionPane.showMessageDialog(this,"SORRY");
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String a="OTHERS";
        try
{
int n=JOptionPane.showConfirmDialog(this,"Are you sure to Vote "+a);
if(n==0)
{
Class.forName("java.sql.DriverManager");
Connection C=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/OVS","root","RRMPS");
Statement S=(Statement)C.createStatement();
String query="select * from VOTINGPAD WHERE PARTYNAME='"+a+"';";
ResultSet r =S.executeQuery(query);
r.next();
String b=r.getString("VOTE");
long c=Long.parseLong(b);
long d=c+1;
Statement Sa=(Statement)C.createStatement();
String query1="update VotingPad set Vote='"+d+"' Where PARTYNAME='"+a+"';";
Sa.executeUpdate(query1);
JOptionPane.showMessageDialog(this,"Thanks! for Voting....Now you can not undo your vote","Thanks",1);
JOptionPane.showMessageDialog(this,"Now please give your precious time for giving feedback of our application ONLINE VOTING MACHINE","REQUEST",1);
{new feedback().setVisible(true);}
this.dispose();}
}
catch(Exception e)
{
JOptionPane.showMessageDialog(this,"SORRY");
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
int i=JOptionPane.showConfirmDialog(this,"Do you Want To Exit");
if(i==0)
{this.dispose();}            // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VOTINGPAD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

}
